/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socketchatbot;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author Sateesh_kaatnam
 */
public class Bot2 extends javax.swing.JFrame {

    /**
     * Creates new form Bot2
     */
    static Socket sb2;
    static DataInputStream b2in;
    static DataOutputStream b2op;
    public Bot2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Bot2MsgArea = new javax.swing.JTextArea();
        Bot2TextField = new javax.swing.JTextField();
        Bot2Send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hey Batman, Superman is online.!");
        setBackground(new java.awt.Color(0, 0, 0));

        Bot2MsgArea.setEditable(false);
        Bot2MsgArea.setBackground(new java.awt.Color(0, 0, 0));
        Bot2MsgArea.setColumns(20);
        Bot2MsgArea.setForeground(new java.awt.Color(51, 255, 0));
        Bot2MsgArea.setLineWrap(true);
        Bot2MsgArea.setRows(5);
        Bot2MsgArea.setCaretColor(new java.awt.Color(0, 0, 0));
        Bot2MsgArea.setDisabledTextColor(new java.awt.Color(51, 255, 0));
        jScrollPane1.setViewportView(Bot2MsgArea);

        Bot2TextField.setBackground(new java.awt.Color(0, 0, 0));
        Bot2TextField.setForeground(new java.awt.Color(51, 255, 0));
        Bot2TextField.setText("Enter Text Here");
        Bot2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot2TextFieldActionPerformed(evt);
            }
        });

        Bot2Send.setBackground(new java.awt.Color(0, 0, 0));
        Bot2Send.setForeground(new java.awt.Color(51, 255, 0));
        Bot2Send.setText("Send");
        Bot2Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot2SendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(Bot2Send)
                .addGap(0, 211, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Bot2TextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bot2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bot2Send)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bot2SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot2SendActionPerformed
        // TODO add your handling code here:
        String msgSend="";
        msgSend=Bot2TextField.getText().trim();
        try {
            b2op.writeUTF(msgSend);
            Bot2MsgArea.append("\nYou: "+msgSend);
        } catch (IOException ex) {
            System.out.println("Error in sending data from Bot1..!");
        }
    }//GEN-LAST:event_Bot2SendActionPerformed

    private void Bot2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bot2TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bot2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bot2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bot2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bot2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bot2().setVisible(true);
            }
        });
        String inpb2="";
        try{
            
            sb2= new Socket("127.0.0.1",1201);
            b2in= new DataInputStream(sb2.getInputStream());
            b2op= new DataOutputStream(sb2.getOutputStream());
            while(!inpb2.equals("exit")){
                inpb2=b2in.readUTF();
                Bot2MsgArea.setText(Bot2MsgArea.getText().trim()+"\nSuperman: "+inpb2);
            }
        }catch (Exception err){
         System.out.println("Error in dispalying Msg in Bot2..!");
        }
        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea Bot2MsgArea;
    private javax.swing.JButton Bot2Send;
    private javax.swing.JTextField Bot2TextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
